### ISSUE TITLE
Dev Plans

### ISSUE THREAD

**Issue by 9am** [9am/use-spotlight#1]
## Project

- [x] Testing [#435cd2f](https://github.com/9am/use-spotlight/commit/435cd2f77cbfcf2f12f5527b3c1bbdad5ad59009)
- [x] CI [#dddaa7e](https://github.com/9am/use-spotlight/commit/dddaa7ea147539ab6ef4892f1c570bccbbdfc342)
- [x] pre-commit hook [#1aac9ad](https://github.com/9am/use-spotlight/commit/1aac9ad4e64794ea4d6510028185ec9dbdec6f04)
- [x] Demos [#9c3edc4](https://github.com/9am/use-spotlight/commit/9c3edc464ef7b39ce8fadf969097da7a9b917fc3)
- [x] README [#9c3edc4](https://github.com/9am/use-spotlight/commit/9c3edc464ef7b39ce8fadf969097da7a9b917fc3)
- [x] Logo [#dddaa7e](https://github.com/9am/use-spotlight/commit/dddaa7ea147539ab6ef4892f1c570bccbbdfc342)
- [ ] lint
- [ ] Changesets
- [ ] Home page

## Bugs

- [x] Fix actor position offset bug causing by stage border-width  [#435cd2f](https://github.com/9am/use-spotlight/commit/435cd2f77cbfcf2f12f5527b3c1bbdad5ad59009)
- [x] Prevent style pollution by `padding` `margin` `z-index`   [#d94df8c](https://github.com/9am/use-spotlight/commit/d94df8c3b3082e5c26d3d317414261363b83a99b)
- [ ] Is there any case that actor has position updated but without any resizing and DOM mutation (css order change)?
    - [x] it will not trigger resize when 'stage' has fixed width or reaches `max-width`. [#6d0b5a8](https://github.com/9am/use-spotlight/commit/6d0b5a85f88ee0ad04e6c0fb0ba66a44f82b80d8)

## Features

- [x] Throttle (options to control the time window) [#dddaa7e](https://github.com/9am/use-spotlight/commit/dddaa7ea147539ab6ef4892f1c570bccbbdfc342)
- [x] Find ways to get rid of the `<div>`, couldn't add `::after` with JS, all I can think of is adding a CSS file [#6964629](https://github.com/9am/use-spotlight/commit/6964629bc97ee9e9241ebef231bba9b3c40750be)
    - [ ] Add test cases for pesudo mode
